CREATE TABLE `ADDRESS_TYPE` (
  `ADDRESS_TYPE_ID` int(11) UNSIGNED NOT NULL,
  `ADDRESS_TYPE_ENUM` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS_TYPE_KWD` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS_TYPE_NAME` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS_TYPE_DESC` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISACTIVE` int(7) NOT NULL DEFAULT '1'
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `ADDRESS_TYPE`
  ADD PRIMARY KEY (`ADDRESS_TYPE_ID`);
