CREATE TABLE `ADDRESS_COUNTRY` (
  `ADDRESS_COUNTRY_ID` int(11) UNSIGNED NOT NULL,
  `ADDRESS_COUNTRY_CODE` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ADDRESS_COUNTRY_NAME` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `ADDRESS_COUNTRY`
  ADD PRIMARY KEY (`ADDRESS_COUNTRY_ID`),
  ADD UNIQUE KEY `ADDRESS_COUNTRY_CODE` (`ADDRESS_COUNTRY_CODE`);
