CREATE TABLE `ADDRESS` (
  `ADDRESS_ID` int(11) UNSIGNED NOT NULL,
  `ADDRESS_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS_DESCRIPTION` text COLLATE utf8mb4_unicode_ci,
  `ADDRESS_STREET_1` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS_STREET_2` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS_STREET_3` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS_CITY` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ADDRESS_STATE_ID` int(11) UNSIGNED NOT NULL,
  `ADDRESS_COUNTRY_ID` int(11) UNSIGNED NOT NULL,
  `ADDRESS_POSTAL` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;