CREATE TABLE `CLIENT_ROLE` (
  `CLIENT_ROLE_ID` int(11) UNSIGNED NOT NULL,
  `CLIENT_ROLE_ENUM` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CLIENT_ROLE_KWD` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CLIENT_ROLE_NAME` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CLIENT_ROLE_DESC` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


