CREATE TABLE `INVENTORY` (
  `INVENTORY_ID` int(11) UNSIGNED NOT NULL,
  `PRODUCT_ID` int(11) UNSIGNED NOT NULL,
  `UOM_SIZE` decimal(10,4) NOT NULL,
  `UOM_SYM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `UOM_STYLE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `INVENTORY_QTY` int(11) NOT NULL,
  `BASIS_PRICE` decimal(10,2) DEFAULT NULL,
  `RETAIL_PRICE` decimal(10,2) DEFAULT NULL,
  `INVENTORY_NOTES` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

ALTER TABLE `INVENTORY`
  ADD PRIMARY KEY (`INVENTORY_ID`);
