CREATE TABLE `INVOICE` (
  `INVOICE_ID` int(11) UNSIGNED NOT NULL,
  `LIVESTREAM_ID` int(11) UNSIGNED DEFAULT NULL,
  `CLIENT_ID` int(11) UNSIGNED NOT NULL,
  `INVOICE_PAYPAL` varchar(50) DEFAULT NULL,
  `INVOICE_DELIVERY_ADDRESS_ID` int(11) UNSIGNED DEFAULT NULL,
  `INVOICE_BILLING_ADDRESS_ID` int(11) UNSIGNED DEFAULT NULL,
  `INVOICE_STATUS_ID` int(11) UNSIGNED NOT NULL DEFAULT '1',
  `INVOICE_NOTES` text COLLATE utf8mb4_unicode_ci,
  `INVOICE_SHIPPING_PRICE` decimal(10,2) DEFAULT NULL,
  `INVOICE_SHIPPING_PALLET` int(7) NOT NULL DEFAULT '0',
  `ISACTIVE` int(7) NOT NULL DEFAULT '1',
  `INSERTDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATEDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `INVOICE`
  ADD PRIMARY KEY (`INVOICE_ID`),
  ADD UNIQUE KEY `INVOICE_PAYPAL` (`INVOICE_PAYPAL`);
