CREATE TABLE `INVOICE_TYPE` (
  `INVOICE_TYPE_ID` int(11) UNSIGNED NOT NULL,
  `INVOICE_TYPE_ENUM` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INVOICE_TYPE_KWD` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INVOICE_TYPE_NAME` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INVOICE_TYPE_DESC` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISACTIVE` int(7) NOT NULL DEFAULT '1'
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
