CREATE TABLE `INVOICE_ITEM` (
  `INVOICE_ID` int(11) UNSIGNED DEFAULT NULL,
  `LIVESTREAM_ID` int(11) UNSIGNED DEFAULT NULL,
  `CLIENT_ID` int(11) UNSIGNED DEFAULT NULL,
  `VENDOR_PRODUCT_ID` int(11) UNSIGNED DEFAULT NULL,
  `SHIPMENT_CONTAINER_ID` int(11) UNSIGNED DEFAULT NULL,
  `INVOICE_ITEM_ID` int(11) UNSIGNED NOT NULL,
  `INVOICE_ITEM_NAME` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INVOICE_ITEM_QTY` int(11) UNSIGNED NOT NULL DEFAULT '1',
  `INVOICE_ITEM_DESC` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INVOICE_ITEM_PRICE` decimal(10,2) DEFAULT NULL,
  `INVOICE_ITEM_UNIT_AMOUNT` decimal(10,2) NOT NULL DEFAULT '0.00',
  `INVOICE_ITEM_PAYPAL_ID` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INVOICE_ITEM_WEIGHT` decimal(10,2) DEFAULT NULL,
  `INVOICE_ITEM_LENGTH` decimal(10,2) DEFAULT NULL,
  `INVOICE_ITEM_WIDTH` decimal(10,2) DEFAULT NULL,
  `INVOICE_ITEM_HEIGHT` decimal(10,2) DEFAULT NULL,
  `INVOICE_ITEM_UOM_MASS` int(11) UNSIGNED DEFAULT NULL,
  `INVOICE_ITEM_UOM_VOLUME` int(11) UNSIGNED DEFAULT NULL,
  `INVOICE_ITEM_NOTES` text COLLATE utf8mb4_unicode_ci,
  `INVOICE_ITEM_TIME` time DEFAULT NULL,
  `ISACTIVE` int(7) NOT NULL DEFAULT '1',
  `INSERTDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATEDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



ALTER TABLE `INVOICE_ITEM`
  ADD PRIMARY KEY (`INVOICE_ID`,`INVOICE_ITEM_ID`);
