CREATE TABLE `INVOICE_ITEM` (
  `INVOICE_ID` int(11) UNSIGNED NOT NULL,
  `INVOICE_ITEM_ID` int(11) UNSIGNED NOT NULL,
  `INVOICE_ITEM_NAME` varchar(200) DEFAULT NULL,
  `INVOICE_ITEM_DESC` varchar(200) DEFAULT NULL,
  `INVOICE_ITEM_PRICE` decimal(10,2) DEFAULT NULL,
  `INVOICE_ITEM_NOTES` text COLLATE utf8mb4_unicode_ci,
  `INVOICE_ITEM_TIME` time DEFAULT NULL,
  `ISACTIVE` int(7) NOT NULL DEFAULT '1',
  `INSERTDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATEDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `INVOICE_ITEM`
  ADD PRIMARY KEY (`INVOICE_ID`,`INVOICE_ITEM_ID`);
