CREATE TABLE `MEMBER_ADDRESS` (
  `MEMBER_ID` int(11) UNSIGNED NOT NULL,
  `ADDRESS_ID` int(11) UNSIGNED NOT NULL,
  `MEMBER_ADDRESS_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MEMBER_ADDRESS_ISPRIMARY` int(7) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `MEMBER_ADDRESS`
  ADD PRIMARY KEY (`MEMBER_ID`,`ADDRESS_ID`);
