CREATE TABLE `NAVIGATION_AREA` (
  `NAVIGATION_AREA_ID` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `NAVIGATION_AREA_PARENT_ID` int(11) UNSIGNED DEFAULT NULL,
  `NAVIGATION_AREA_KWD` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAVIGATION_AREA_CANONICAL` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAVIGATION_AREA_TITLE` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAVIGATION_AREA_DESCRIPTION` text COLLATE utf8mb4_unicode_ci,
  `NAVIGATION_AREA_IMGURL` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAVIGATION_AREA_PRIORITY` int(7) NOT NULL DEFAULT '0',
  `ISACTIVE` int(7) NOT NULL DEFAULT '1'
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `NAVIGATION_AREA`
  ADD PRIMARY KEY (`NAVIGATION_AREA_ID`);
