CREATE TABLE `PAGE` (
  `PAGE_ID` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `PAGE_PARENT_ID` int(11) UNSIGNED DEFAULT NULL,
  `PAGE_TYPE_ID` int(11) UNSIGNED DEFAULT NULL,
  `PAGE_CANONICAL` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PAGE_TITLE` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PAGE_DESCRIPTION` text COLLATE utf8mb4_unicode_ci,
  `PAGE_IMGURL` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PAGE_PRIORITY` int(7) NOT NULL DEFAULT '0',
  `PAGE_ISACTIVE` int(7) NOT NULL DEFAULT '1'
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
