CREATE TABLE `PRODUCT_TAG` (
  `PRODUCT_ID` int(11) UNSIGNED NOT NULL,
  `TAG_ID` int(11) UNSIGNED NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `PRODUCT_TAG`
  ADD PRIMARY KEY (`PRODUCT_ID`,`TAG_ID`);
