CREATE TABLE `PRODUCT` (
  `PRODUCT_ID` int(11) UNSIGNED NOT NULL,
  `PRODUCT_STATUS_ID` int(11) UNSIGNED NOT NULL DEFAULT '1',
  `PRODUCT_KWD` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PRODUCT_NAME` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PRODUCT_IMGURL` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PRODUCT_DESC` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PRIORITY` int(11) NOT NULL DEFAULT '0',
  `ISACTIVE` int(7) NOT NULL DEFAULT '1',
  `INSERTDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATEDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `PRODUCT`
  ADD PRIMARY KEY (`PRODUCT_ID`),
  ADD UNIQUE KEY `PRODUCT_KWD` (`PRODUCT_KWD`);
