CREATE TABLE `PRODUCT` (
  `PRODUCT_ID` int(11) UNSIGNED NOT NULL,
  `PRODUCT_STATUS_ID` int(11) UNSIGNED NOT NULL DEFAULT '1',
  `PRODUCT_KWD` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `PRODUCT_NAME` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PRODUCT_IMGURL` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PRODUCT_DESCRIPTION` text COLLATE utf8mb4_unicode_ci,
  `ISACTIVE` int(7) NOT NULL DEFAULT '1',
  `INSERTDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATEDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;