CREATE TABLE `REQUEST` (
  `REQUEST_ID` int(11) UNSIGNED NOT NULL,
  `CLIENT_ID` int(11) UNSIGNED DEFAULT NULL,
  `MEMBER_ID` int(11) UNSIGNED DEFAULT NULL,
  `VENDOR_ID` int(11) UNSIGNED DEFAULT NULL,
  `REQUEST_PARENT_ID` int(11) UNSIGNED DEFAULT NULL,
  `REQUEST_STATUS_ID` int(11) UNSIGNED NOT NULL DEFAULT '1',
  `REQUEST_TITLE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REQUEST_TEXT` text COLLATE utf8mb4_unicode_ci,
  `REQUEST_RESPONSE` text COLLATE utf8mb4_unicode_ci,
  `REQUEST_PRIORITY` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `ISACTIVE` int(7) NOT NULL DEFAULT '1',
  `INSERTDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATEDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
