CREATE TABLE `SHIPMENT_CONTAINER_TYPE` (
  `SHIPMENT_CONTAINER_TYPE_ID` int(11) UNSIGNED NOT NULL,
  `SHIPMENT_CONTAINER_KWD` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SHIPMENT_CONTAINER_NAME` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SHIPMENT_CONTAINER_DESC` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SHIPMENT_CONTAINER_COST` decimal(10,2) DEFAULT NULL,
  `SHIPMENT_CONTAINER_LENGTH` decimal(10,2) DEFAULT NULL,
  `SHIPMENT_CONTAINER_WIDTH` decimal(10,2) DEFAULT NULL,
  `SHIPMENT_CONTAINER_HEIGHT` decimal(10,2) DEFAULT NULL,
  `SHIPMENT_CONTAINER_MAX_WEIGHT` decimal(10,2) UNSIGNED NOT NULL DEFAULT '0.00',
  `ISACTIVE` int(7) NOT NULL DEFAULT '1'
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
