CREATE TABLE `UOM` (
  `UOM_ID` int(11) UNSIGNED NOT NULL,
  `UOM_SYM` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `UOM_NAME` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `UOM_IS_METRIC` int(7) UNSIGNED NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `UOM`
  ADD PRIMARY KEY (`UOM_ID`),
  ADD UNIQUE KEY `UOM_SYM` (`UOM_SYM`);
