CREATE TABLE `VENDOR_ROLE` (
  `VENDOR_ROLE_ID` int(11) UNSIGNED NOT NULL,
  `VENDOR_ROLE_ENUM` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `VENDOR_ROLE_KWD` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `VENDOR_ROLE_NAME` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `VENDOR_ROLE_DESC` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `VENDOR_ROLE`
  ADD PRIMARY KEY (`VENDOR_ROLE_ID`);

